server.port: 9966
spring.profiles: default
xk.msa.ca.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://360ser.com
  tokenSigningKey: xkhasanxm8EV6Hy5RMFK4EEACIDAwQus
  
spring.datasource: 
  url: jdbc:mysql://192.168.118.10:3306/testsm?useUnicode=true&useSSL=false
  username: root
  password: "!Qaz2wsx"
  driver-class-name: com.mysql.jdbc.Driver

  
  
  
  